import {
  FaSun,
  FaMoon,
  FaCloudSun,
  FaCloudMoon,
  FaCloud,
  FaCloudShowersHeavy,
  FaCloudRain,
  FaCloudMoonRain,
  FaBolt,
  FaSnowflake,
  FaSmog,
} from "react-icons/fa";

export const weatherIconMapping = {
  "01d": <FaSun size={60} color="orange" />,
  "01n": <FaMoon size={60} color="orange" />,
  "02d": <FaCloudSun size={60} color="grey" />,
  "02n": <FaCloudMoon size={60} color="grey" />,
  "03d": <FaCloud size={60} color="grey" />,
  "03n": <FaCloud size={60} color="grey" />,
  "04d": <FaCloud size={60} color="grey" />,
  "04n": <FaCloud size={60} color="grey" />,
  "09d": <FaCloudShowersHeavy size={60} color="blue" />,
  "09n": <FaCloudShowersHeavy size={60} color="blue" />,
  "10d": <FaCloudRain size={60} color="blue" />,
  "10n": <FaCloudMoonRain size={60} color="blue" />,
  "11d": <FaBolt size={60} color="yellow" />,
  "11n": <FaBolt size={60} color="yellow" />,
  "13d": <FaSnowflake size={60} color="blue" />,
  "13n": <FaSnowflake size={60} color="blue" />,
  "50d": <FaSmog size={60} color="grey" />,
  "50n": <FaSmog size={60} color="grey" />,
};
